"""User settings API -- stores per-user client configuration."""
import json
import logging
import os
from typing import Optional
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session
from sqlalchemy import Column, Integer, Text, ForeignKey
from app.database import get_db, engine
from app.models import Base
from app.models import User
from app.auth import get_current_user
from app.config import PROJECT_ROOT

logger = logging.getLogger(__name__)


class UserSettings(Base):
    __tablename__ = "user_settings"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False)
    settings_json = Column(Text, nullable=False, default="{}")


Base.metadata.create_all(bind=engine)

router = APIRouter(prefix="/api/settings", tags=["settings"])

# Separate router (no prefix) for /api/agent/* paths (design §6.4: client auto-update)
# These conceptually belong with settings (client version config) but use a different URL space.
agent_update_router = APIRouter(tags=["agent-update"])


class SettingsPayload(BaseModel):
    server_url: Optional[str] = None
    script_download_dir: Optional[str] = None
    output_dir: Optional[str] = None
    default_browser_path: Optional[str] = None
    browser_debug_port: Optional[int] = None
    proxy: Optional[str] = None


@router.get("")
def get_settings(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    row = db.query(UserSettings).filter(UserSettings.user_id == current_user.id).first()
    if not row:
        return {}
    try:
        return json.loads(row.settings_json)
    except (json.JSONDecodeError, OSError):
        return {}


@router.put("")
def update_settings(
    req: SettingsPayload,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    row = db.query(UserSettings).filter(UserSettings.user_id == current_user.id).first()
    data = json.dumps(req.dict(), ensure_ascii=False)
    if row:
        row.settings_json = data
    else:
        row = UserSettings(user_id=current_user.id, settings_json=data)  # type: ignore[call-arg]
        db.add(row)
    db.commit()

    # Sync to client_config.json
    config_path = os.path.join(PROJECT_ROOT, "client_config.json")
    try:
        client_cfg = {}
        if os.path.isfile(config_path):
            with open(config_path, "r", encoding="utf-8") as f:
                client_cfg = json.load(f)
        updates = req.dict(exclude_none=True)
        client_cfg.update(updates)
        with open(config_path, "w", encoding="utf-8") as f:
            json.dump(client_cfg, f, indent=2, ensure_ascii=False)
    except (json.JSONDecodeError, OSError) as e:
        logger.warning("Failed to sync client_config.json: %s", e)

    return {"message": "设置已保存"}


@router.delete("")
def reset_settings(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    row = db.query(UserSettings).filter(UserSettings.user_id == current_user.id).first()
    if row:
        db.delete(row)
        db.commit()

    config_path = os.path.join(PROJECT_ROOT, "client_config.json")
    try:
        if os.path.isfile(config_path):
            os.remove(config_path)
    except OSError as e:
        logger.warning("Failed to remove client_config.json: %s", e)

    return {"message": "设置已重置"}


@router.get("/client-version")
def client_version():
    """Return current client version info for auto-update checks."""
    config_path = os.path.join(PROJECT_ROOT, "config.json")
    version = "1.0.0"
    if os.path.isfile(config_path):
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            version = cfg.get("client_version", version)
        except (json.JSONDecodeError, OSError):
            pass
    return {"version": version}


# --- Agent auto-update (design §5.8, §6.4) ---
# Client packages are expected under PROJECT_ROOT/client_dist/{version}/client.zip
# or PROJECT_ROOT/client_dist/client-{version}.zip. Generated by the build/packaging step.
_CLIENT_DIST_DIR = os.path.join(PROJECT_ROOT, "client_dist")


def _resolve_client_package(version: str):
    """Locate client install package for a given version. Returns absolute path or None."""
    if not version or not all(c.isalnum() or c in "._-" for c in version):
        return None  # sanitize: reject path-like version strings
    candidates = [
        os.path.join(_CLIENT_DIST_DIR, "client-{}.zip".format(version)),
        os.path.join(_CLIENT_DIST_DIR, version, "client.zip"),
        os.path.join(_CLIENT_DIST_DIR, "{}.zip".format(version)),
    ]
    for c in candidates:
        if os.path.isfile(c):
            return c
    return None


@agent_update_router.get("/api/agent/check-update")
def check_agent_update(version: str = ""):
    """Compare requester's client version with the latest published version."""
    config_path = os.path.join(PROJECT_ROOT, "config.json")
    latest = "1.0.0"
    if os.path.isfile(config_path):
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            latest = cfg.get("client_version", latest)
        except (json.JSONDecodeError, OSError):
            pass

    def _parts(v):
        try:
            return [int(x) for x in v.split(".")]
        except (ValueError, AttributeError):
            return [0]

    update_available = _parts(latest) > _parts(version or "0.0.0")
    package_present = _resolve_client_package(latest) is not None
    return {
        "latest_version": latest,
        "current_version": version,
        "update_available": update_available,
        "package_available": package_present,
    }


@agent_update_router.get("/api/agent/download/{version}")
def download_agent_package(version: str):
    """Download the client install package for a specific version."""
    from fastapi import HTTPException
    from fastapi.responses import FileResponse
    package = _resolve_client_package(version)
    if not package:
        raise HTTPException(status_code=404, detail="找不到版本 {} 的客户端安装包".format(version))
    return FileResponse(
        package,
        filename="client-{}.zip".format(version),
        media_type="application/zip",
    )
